### ISSUE TITLE
ExpansionError during parsing eglstreams-kms-example

### ISSUE THREAD

**Issue by leonheld** [OE4T/tegra-demo-distro#228]
Hi there 👋🏻 

I got this error during a build. It's most likely a problem upstream, but I'll open the issue here because I pretend looking into it later on if this is not a common problem. For now I just removed the eglstreams-kms-example recipes and took it out of the packagegroup.

System: docker running Ubuntu 18.04.

Logs:

```
ubuntu@b1c3a3ad4551:~/volume/tegra-demo-distro$ bitbake demo-image-full
ERROR: ExpansionError during parsing /home/ubuntu/volume/tegra-demo-distro/layers/meta-tegra-community/recipes-test/eglstreams/eglstreams-kms-example_git.bb | ETA:  0:02:13
Traceback (most recent call last):
  File "/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/lib/bb/fetch2/__init__.py", line 1175, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fd920f31a90>, d=<bb.data_smart.DataSmart object at 0x7fd9210c2630>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/lib/bb/fetch2/__init__.py", line 1590, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7fd920f31a90>, d=<bb.data_smart.DataSmart object at 0x7fd9210c2630>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/lib/bb/fetch2/git.py", line 705, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7fd920f31a90>, d=<bb.data_smart.DataSmart object at 0x7fd9210c2630>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/lib/bb/fetch2/git.py", line 694, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7fd920f31a90>, d=<bb.data_smart.DataSmart object at 0x7fd9210c2630>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/lib/bb/fetch2/__init__.py", line 892, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export PATH="/home/ubuntu/volume/tegra-demo-distro/layers/scripts:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/aarch64-oe4t-linux:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/bin:/home/ubuntu/volume/tegra-demo-distro/tmp/hosttools"; export HOME="/home/ubuntu"; git -c core.fsyncobjectfiles=0 ls-remote "https://github.com/madisongh/eglstreams-kms-example" ', d=<bb.data_smart.DataSmart object at 0x7fd920f31cf8>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/ubuntu/volume/tegra-demo-distro/layers/scripts:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/aarch64-oe4t-linux:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/ubuntu/volume/tegra-demo-distro/tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/ubuntu/volume/tegra-demo-distro/repos/poky/bitbake/bin:/home/ubuntu/volume/tegra-demo-distro/tmp/hosttools"; export HOME="/home/ubuntu"; git -c core.fsyncobjectfiles=0 ls-remote "https://github.com/madisongh/eglstreams-kms-example"  failed with exit code 128, no output

WARNING: /home/ubuntu/volume/tegra-demo-distro/layers/meta-python/recipes-devtools/python/python3-pint_0.11.bb: Cooker received SIGTERM, shutting down...
WARNING: /home/ubuntu/volume/tegra-demo-distro/layers/meta-python/recipes-devtools/python/python3-scapy_0.25.bb: Cooker received SIGTERM, shutting down...
WARNING: /home/ubuntu/volume/tegra-demo-distro/layers/meta-virtualization/recipes-extended/images/uxen-guest-image-minimal.bb: Cooker received SIGTERM, shutting down...`

**Comment by ichergui** [comment]
Hey @leonheld 

Thanks reporting this issue. I will take a look and will keep you updated.

**Comment by ichergui** [comment]
@leonheld 
Which branch you are using ?
I tried master branch and it is working fine 

```
➜  build-orin-agx git:(master)  (master)tree tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/1.0+gitAUTOINC+1667ca369f-r0/packages-split/eglstreams-kms-example
tmp/work/armv8a_tegra-oe4t-linux/eglstreams-kms-example/1.0+gitAUTOINC+1667ca369f-r0/packages-split/eglstreams-kms-example
└── usr
    └── bin
        └── eglstreams-kms-example

2 directories, 1 file
➜  build-orin-agx git:(master)  (master)
```

**Comment by ichergui** [comment]
@leonheld 
Any updates ?

**Comment by ichergui** [comment]
Closing this issue because of no updates.
If the issue persist please open new ticket
